import React, { useState } from 'react';
import { useAgent } from '../../context/AgentContext';
import {
  Code2,
  Play,
  Copy,
  Check,
  Download,
  Terminal,
  Sparkles,
  Zap,
  RotateCcw,
  Bot,
  Layers,
  FileCode
} from 'lucide-react';

const CODE_TEMPLATES = {
  react: {
    title: 'React Real-time Voice WebRTC Hook',
    lang: 'typescript',
    code: `import { useState, useEffect, useRef } from 'react';

/**
 * useRealtimeVoiceAgent - WebRTC & Speech Hook for AURQO AI
 */
export function useRealtimeVoiceAgent(agentId: string) {
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [latencyMs, setLatencyMs] = useState(120);

  const startStreaming = async () => {
    console.log(\`Connecting WebRTC LiveKit channel for agent: \${agentId}\`);
    // Connect WebRTC stream with <200ms audio budget
  };

  return { isSpeaking, transcript, latencyMs, startStreaming };
}`
  },
  python: {
    title: 'FastAPI High-Performance Agent Server',
    lang: 'python',
    code: `from fastapi import FastAPI, WebSocket, Depends
from pydantic import BaseModel

app = FastAPI(title="AURQO Neural Voice Engine")

class AgentPayload(BaseModel):
    agent_id: str
    voice_persona: str = "shimmer"
    memory_saving: bool = True

@app.websocket("/ws/voice-stream/{agent_id}")
async def voice_stream_endpoint(websocket: WebSocket, agent_id: str):
    await websocket.accept()
    # Stream low-latency Opus audio packets
    await websocket.send_json({"status": "connected", "latency_ms": 115})`
  },
  sql: {
    title: 'High-Throughput Vector Memory & Indexing',
    lang: 'sql',
    code: `-- AURQO Vector Memory Storage & Retrieval Schema
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE agent_persistent_memory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id VARCHAR(64) NOT NULL,
    conversation_id VARCHAR(64) NOT NULL,
    memory_context TEXT NOT NULL,
    embedding vector(1536),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_agent_embedding_hnsw 
ON agent_persistent_memory USING hnsw (embedding vector_cosine_ops);`
  }
};

export function AICodeView() {
  const { setCurrentView } = useAgent();
  const [selectedLang, setSelectedLang] = useState('react');
  const [prompt, setPrompt] = useState('');
  const [currentCode, setCurrentCode] = useState(CODE_TEMPLATES.react.code);
  const [isCopied, setIsCopied] = useState(false);
  const [isRunning, setIsRunning] = useState(false);
  const [consoleOutput, setConsoleOutput] = useState('Ready to compile & test code.');

  const handleLangChange = (langKey) => {
    setSelectedLang(langKey);
    setCurrentCode(CODE_TEMPLATES[langKey].code);
    setConsoleOutput(`Switched template to ${CODE_TEMPLATES[langKey].title}`);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(currentCode);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleRun = () => {
    setIsRunning(true);
    setConsoleOutput('⚡ Transpiling and executing code in sandbox...');
    setTimeout(() => {
      setIsRunning(false);
      setConsoleOutput(`[Execution Success] ✓ 0 errors found. Tested in 38ms. Memory footprint: 1.4MB.`);
    }, 600);
  };

  const handleGenerate = (e) => {
    e.preventDefault();
    if (!prompt.trim()) return;
    setIsRunning(true);
    setConsoleOutput(`🤖 Synthesizing clean code for: "${prompt}"...`);
    setTimeout(() => {
      setIsRunning(false);
      setCurrentCode(`// Generated by AURQO AI Code Generator
// Request: ${prompt}

export async function executeAgentWorkflow() {
  const response = await fetch('/api/v1/agent/run', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ prompt: "${prompt}" })
  });
  return await response.json();
}`);
      setConsoleOutput(`✓ Generated clean, type-safe architecture for "${prompt}".`);
      setPrompt('');
    }, 700);
  };

  return (
    <div className="ecosystem-view-page">
      {/* View Header */}
      <div className="ecosystem-view-header">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="eco-badge-tag">Full-Stack & Systems</span>
          </div>
          <h2 className="eco-title">{'</>'} AI Code Generator & Debugger</h2>
          <p className="eco-sub">
            Generate production-ready code, refactor algorithms, debug errors, and optimize queries across 30+ languages.
          </p>
        </div>

        <button onClick={() => setCurrentView('agent-hub')} className="btn-eco-agent-cta">
          <Bot size={16} />
          <span>Launch AI Agent Studio</span>
        </button>
      </div>

      {/* Code Workbench Grid */}
      <div className="code-workbench-grid">
        {/* Left / Top Controls & Code Box */}
        <div className="code-editor-card">
          <div className="editor-topbar">
            {/* Language Tabs */}
            <div className="lang-tabs-group">
              <button
                className={`lang-tab-btn ${selectedLang === 'react' ? 'active' : ''}`}
                onClick={() => handleLangChange('react')}
              >
                TypeScript / React
              </button>
              <button
                className={`lang-tab-btn ${selectedLang === 'python' ? 'active' : ''}`}
                onClick={() => handleLangChange('python')}
              >
                Python / FastAPI
              </button>
              <button
                className={`lang-tab-btn ${selectedLang === 'sql' ? 'active' : ''}`}
                onClick={() => handleLangChange('sql')}
              >
                PostgreSQL / Vectors
              </button>
            </div>

            {/* Action Buttons */}
            <div className="editor-actions-row">
              <button onClick={handleCopy} className="btn-editor-action" title="Copy Code">
                {isCopied ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
                <span>{isCopied ? 'Copied!' : 'Copy'}</span>
              </button>
              <button onClick={handleRun} disabled={isRunning} className="btn-editor-run">
                <Play size={14} />
                <span>{isRunning ? 'Running...' : 'Run Code'}</span>
              </button>
            </div>
          </div>

          {/* Editor Body */}
          <textarea
            value={currentCode}
            onChange={(e) => setCurrentCode(e.target.value)}
            className="code-textarea-editor"
            rows={14}
            spellCheck="false"
          />

          {/* Terminal Console Output */}
          <div className="editor-console-box">
            <div className="console-header">
              <div className="flex items-center gap-2">
                <Terminal size={14} className="text-purple-500" />
                <span className="console-title">Execution Console & Linters</span>
              </div>
              <span className="console-status-dot">● Active</span>
            </div>
            <pre className="console-log-text">{consoleOutput}</pre>
          </div>
        </div>

        {/* Prompt Input Generator */}
        <div className="code-prompt-card">
          <h4 className="prompt-card-heading">Describe Code to Generate or Debug</h4>
          <p className="prompt-card-sub">
            Ask for algorithm implementations, API endpoints, bug fixes, or SQL optimizations.
          </p>

          <form onSubmit={handleGenerate} className="code-input-form">
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. Write a custom WebSocket reconnect handler with exponential backoff..."
              rows={3}
              className="aurqo-input-field mb-3"
            />
            <button type="submit" disabled={!prompt.trim() || isRunning} className="btn-create-agent-submit">
              <Sparkles size={16} />
              <span>Generate Clean Code</span>
            </button>
          </form>

          {/* Quick Prompts */}
          <div className="quick-code-prompts-list mt-4">
            <span className="text-xs font-bold text-gray-500 uppercase">Quick Starters:</span>
            <div className="flex flex-wrap gap-2 mt-2">
              <button
                type="button"
                onClick={() => setPrompt('Create a Redis cache layer for high-concurrency requests')}
                className="btn-quick-prompt"
              >
                Redis Cache Layer
              </button>
              <button
                type="button"
                onClick={() => setPrompt('Write a Docker multi-stage build for React Vite production')}
                className="btn-quick-prompt"
              >
                Docker Multi-stage
              </button>
              <button
                type="button"
                onClick={() => setPrompt('Build a debounce hook in TypeScript with unit tests')}
                className="btn-quick-prompt"
              >
                Debounce Hook + Tests
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
